name: Windows

on:
  push:
    branches-ignore:
    - 'release/[0-9]+.[0-9]+.[0-9]+'
  pull_request:


jobs:
  pre_job:
    name: Build Preparation
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check_skip.outputs.should_skip }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Check for build skip
        id: check_skip
        run: bash ci/check-skip.sh
  build:
    name: Build (Visual Studio)
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Python packages
      uses: insightsengineering/pip-action@v2
      with:
        packages: |
          b2sdk
          PyNaCl
    - name: Prepare build
      run: .\ci\win-buildgen.ps1
    - name: Turn on problem matcher
      uses: ammaraskar/msvc-problem-matcher@master
    - name: Run build
      run: cmake --build .\build\ --config RelWithDebInfo --parallel
    - name: Prepare artifact
      run: .\ci\win-artifact.ps1
    - name: Stage artifacts for testing
      run: .\ci\win-prepare-demotest.ps1
    - name: Download OdaTests and Testing Resources
      id: get-odatests
      run: .\ci\win-get-demotester.ps1
      env:
        DEMOTESTER_URL: ${{ vars.DEMOTESTER_DOWNLOAD_URL }}
        DEMORESOURCES_URL: ${{ vars.DEMORESOURCES_DOWNLOAD_URL }}
      continue-on-error: true
    - name: Decrypt IWADs
      if: steps.get-odatests.outcome == 'success'
      run: |
        python .\secret.py decrypt plutonia
        python .\secret.py decrypt tnt
        python .\secret.py decrypt doom
        python .\secret.py decrypt doom1
        python .\secret.py decrypt doom2
      env:
        SECRET_KEY: ${{ secrets.DEMOTESTER_IWAD_KEY }}
      working-directory: .\build\demotester
    - name: Run OdaTests
      id: odatests
      if: steps.get-odatests.outcome == 'success'
      shell: pwsh
      run: |
        python .\odatestcases.py
      env:
        ODAMEX_BIN: ..\demotest\odamex.exe
      working-directory: .\build\demotester
      continue-on-error: true
    - name: Read OdaTests results
      if: steps.odatests.conclusion == 'success'
      id: odatests-results
      shell: pwsh
      run: |
        $csvData = Import-Csv -Path .\odatests_results_summary.csv
        echo "tests_total=$($csvData[0].total)" >> $env:GITHUB_OUTPUT
        echo "tests_passed=$($csvData[0].passed)" >> $env:GITHUB_OUTPUT
      working-directory: .\build\demotester
    - name: Notify Discord
      if: env.DISCORD_URL != '' && steps.odatests.conclusion == 'success'
      uses: ./.github/actions/odatests-notify
      with:
        demos-run: ${{ steps.odatests-results.outputs.tests_total }}
        demos-passed: ${{ steps.odatests-results.outputs.tests_passed }}
        discord-url: ${{ env.DISCORD_URL }}
      env:
        DISCORD_URL: ${{ secrets.ODATESTS_WEBHOOK_URL }}
    - name: Upload artifact to B2
      run: python .\ci\upload-b2.py .\build\archive Win-x64
      env:
        B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
        B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
        B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
    - name: Upload artifact to Github
      uses: actions/upload-artifact@v4
      with:
        name: Odamex-Win-x64
        path: 'build/artifact/*'
  build-x32:
    name: Build (Visual Studio, 32-bit)
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Python packages
      uses: insightsengineering/pip-action@v2
      with:
        packages: |
          b2sdk
    - name: Prepare build
      run: .\ci\win-x32-buildgen.ps1
    - name: Run build
      run: cmake --build .\build-x32\ --config RelWithDebInfo --parallel
    - name: Prepare artifact
      run: .\ci\win-x32-artifact.ps1
    - name: Upload artifact to B2
      run: python .\ci\upload-b2.py .\build-x32\archive Win-x32
      env:
        B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
        B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
        B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
    - name: Upload artifact to Github
      uses: actions/upload-artifact@v4
      with:
        name: Odamex-Win-x32
        path: 'build-x32/artifact/*'
  # build-mingw:
  #   name: Build (MinGW)
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout source
  #     uses: actions/checkout@v4
  #   - name: Checkout submodules
  #     run: git submodule update --init --recursive
  #   - name: Install packages
  #     uses: crazy-max/ghaction-chocolatey@v1
  #     with:
  #       args: install ninja
  #   - name: Prepare build
  #     run: .\ci\win-mingw-buildgen.ps1
  #   - name: Run build
  #     run: cmake --build .\build-gcc\
